from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello():
    return "hello if you can see me I was generated by AI"

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
